USE CATALOGO;

SELECT * FROM FILME
SELECT * FROM GENERO

SELECT idFilme,nomeFilme,nomeGenero
FROM FILME
LEFT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero

SELECT idFilme,nomeFilme,nomeGenero
FROM FILME
RIGHT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero

SELECT * 
FROM FILME
INNER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero

SELECT *
FROM FILME
FULL OUTER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero
