CREATE DATABASE ASSISTENCIA_TECNICA

USE ASSISTENCIA_TECNICA

CREATE TABLE MICROMANU(
	idNegocio TINYINT PRIMARY KEY IDENTITY,
	CNPJ CHAR(18) NOT NULL UNIQUE,
	Endereco VARCHAR(25) NOT NULL
);

CREATE TABLE OPERADORES(
	idOperador SMALLINT PRIMARY KEY IDENTITY,
	nome VARCHAR(50) NOT NULL,
	idNegocio TINYINT FOREIGN KEY REFERENCES MICROMANU(idNegocio)
);

CREATE TABLE CLIENTE(
	idCliente INT PRIMARY KEY IDENTITY,
	nome VARCHAR(50) NOT NULL
);

CREATE TABLE EQUIPAMENTO(
	idEquipamento INT PRIMARY KEY IDENTITY,
	tipo_Marca VARCHAR(50) NOT NULL,
	defeito VARCHAR(100) NOT NULL,
	idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente)
);

CREATE TABLE CONSERTO(
	idConserto INT PRIMARY KEY IDENTITY,
	idOperador SMALLINT FOREIGN KEY REFERENCES OPERADORES(idOperador),
	idEquipamento INT FOREIGN KEY REFERENCES EQUIPAMENTO(idEquipamento),
	dataConserto DATE NOT NULL,
);

