USE OPTUS;

SELECT * FROM GRAVADORA
SELECT * FROM USUARIO
SELECT * FROM TIPOUSUARIO
SELECT * FROM ALBUM
SELECT * FROM ARTISTA
SELECT * FROM TIPOESTILO
SELECT * FROM ESTILO
SELECT * FROM CONDICAO

-- VISUALIZAÇÃO DE SOMENTE USUARIOS ADMINISTRADORES
SELECT idUsuario,nomeUsuario,email,idGravadora FROM USUARIO 
WHERE idTipoUsuario = 1;

-- VISUALIZAÇÃO DE ALBUNS LANÇADOS NESSE ANO
SELECT * FROM ALBUM 
WHERE dataLancamento > '20210101';

-- VISUALIZAR DADOS DOS USUARIOS ATRAVES DO EMAIL E SENHA
SELECT 

-- VISUALIZAR OS ALBUNS ATIVOS E SEUS DADOS
SELECT titulo FROM ALBUM
RIGHT JOIN ESTILO
ON ALBUM.idAlbum = ESTILO.idAlbum


RIGHT JOIN ARTISTA
ON ALBUM.idAlbum = ARTISTA.idAlbum
WHERE idCondicao = 1;