CREATE DATABASE OPTUS;

USE OPTUS;

ALTER TABLE USUARIO
ADD idGravadora TINYINT FOREIGN KEY REFERENCES GRAVADORA(idGravadora)
 
CREATE TABLE TIPOUSUARIO(
 idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
 tipoUsuario VARCHAR(20) NOT NULL UNIQUE);

CREATE TABLE USUARIO(
 idUsuario SMALLINT PRIMARY KEY IDENTITY,
 idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
 nomeUsuario VARCHAR(100) NOT NULL UNIQUE,
 email VARCHAR(80) NOT NULL UNIQUE,
	 senha CHAR(8) NOT NULL UNIQUE);

CREATE TABLE ARTISTA(
 idArtista SMALLINT PRIMARY KEY IDENTITY,
 idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
 nomeArtista VARCHAR(18) NOT NULL UNIQUE);

CREATE TABLE CONDICAO(
 idCondicao TINYINT PRIMARY KEY IDENTITY,
 tipoCondicao VARCHAR(12) NOT NULL);

CREATE TABLE ALBUM(
 idAlbum SMALLINT PRIMARY KEY IDENTITY,
 idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
 idCondicao TINYINT FOREIGN KEY REFERENCES CONDICAO(idCondicao),
 titulo VARCHAR(50) NOT NULL UNIQUE,
 dataLancamento DATE NOT NULL UNIQUE,
 localizacao VARCHAR(150) NOT NULL UNIQUE,
 tempo TIME NOT NULL UNIQUE);

CREATE TABLE TIPOESTILO(
 idTipoEstilo TINYINT PRIMARY KEY IDENTITY,
 nomeEstilo VARCHAR(25) NOT NULL UNIQUE);

CREATE TABLE ESTILO(
 idEstilo TINYINT PRIMARY KEY IDENTITY,
 idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
 idTipoEstilo TINYINT FOREIGN KEY REFERENCES TIPOESTILO(idTipoEstilo));

