USE CATALOGO;

SELECT * FROM PESSOA;
SELECT * FROM TELEFONE;
SELECT * FROM EMAIL;
SELECT * FROM CNH;

SELECT nomePessoa,numeroTelefone,endeEmail,numCNH
FROM PESSOA
LEFT JOIN TELEFONE
ON PESSOA.idPessoa = TELEFONE.idPessoa
LEFT JOIN EMAIL
ON PESSOA.idPessoa = EMAIL.idPessoa
LEFT JOIN CNH
ON PESSOA.idPessoa = CNH.idPessoa
